### PR TITLE
Load static resources from Toolforge CDNjs

### PR DESCRIPTION
**Pull request by lucaswerkmeister**
I noticed this repository doesn’t have a license yet, and if we want to add one, it’s probably better not to have any external files in the repository. (`.gitignore` excludes `static/`, but somehow the files were still added.)

CC @wetneb.

### CODE REVIEW

**Comment by lucaswerkmeister** [comment]
Note: I haven’t updated the README yet, because I don’t understand the “configure static files” part.

**Comment by wetneb** [comment]
Thanks! I'll investigate why HTML5 validation fails here.

**Comment by lucaswerkmeister** [comment]
Oops, sorry

**Comment by wetneb** [comment]
@lucaswerkmeister @lydiapintscher any suggestion for the license? MIT for instance?

**Comment by lucaswerkmeister** [comment]
No strong opinion from me, it’s your code :)

**Pull request merged**
